.\" Jean II - HPLB - 96
.\" iwspy.8
.\"
.TH IWSPY 8 "31 October 1996" "net-tools" "Linux Programmer's Manual"
.\"
.\" NAME part
.\"
.SH NAME
iwspy \- Get wireless statistics from specific nodes
.\"
.\" SYNOPSIS part
.\"
.SH SYNOPSIS
.BI "iwspy " interface
.br
.BI "iwspy " interface " [+] " IPADDR " | " HWADDR " [...]"
.br
.BI "iwspy " interface " off"
.\"
.\" DESCRIPTION part
.\"
.SH DESCRIPTION
.B Iwspy
is used to set a list of addresses in a wireless network interface and
to read back quality of link information for each of those. This
information is the same as the one available in
.I /proc/net/wireless
: quality of the link, signal strength and noise level.
.PP
This information is updated each time a new packet is received, so
each address of the list add some overhead in the driver.
.PP
Note the this functionality work only for node part of the current
wireless cells.
.\"
.\" PARAMETER part
.\"
.SH PARAMETERS
You may set any number of addresses up to 8.
.TP
.B IPADDR
Set an IP address, or in some cases a domain name. As the hardware
work with hardware addresses,
.B iwspy
will translate this address through
.IR ARP .
In some case, this address might not be in the ARP cache and
.B iwspy
will fail. In those case,
.IR ping (8)
this address and retry.
.TP
.B HWADDR
Set a hardware (MAC) address (this address is not translated & checked
like the IP one). The address must contain a semicolon
.RB ( : )
to be recognised as a hardware address.
.TP
.B +
Add the new set of addresses at the end of the current list instead of
replacing it. The address list is unique for each device, so each user
should use this option to avoid conflicts.
.TP
.B off
Remove the current list of addresses and disable the spy functionality
.\"
.\" FILES part
.\"
.SH FILES
.I /proc/net/wireless
.\"
.\" SEE ALSO part
.\"
.SH SEE ALSO
.BR iwconfig (8),
.BR ifconfig (8),
.BR iwlist (8).
.BR iwpriv (8).

